Sw_Trazabilidad/Controllers/AdministracionController.cs
using Sw_Trazabilidad.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sw_Trazabilidad.Controllers
{

    public class AdministracionController : Controller
    {
        private readonly Contexto db = new Contexto();
        // GET: Administracion
        public ActionResult NuevaMateriaPrima()
        {
            var tiposMP = db.TiposMateriaPrima.ToList();
            ViewBag.TiposMP = tiposMP;
            return View();
        }

        public ActionResult NuevoProducto()
        {
            var mp = db.MateriasPrimas.ToList();
            ViewBag.MPrimas = mp;
            return View();
        }

        public ActionResult NuevoTipoMateriaP()
        {
            return View();
        }

        public ActionResult NuevaCosecha()
        {
            return View();
        }

        public ActionResult NuevoGramaje()
        {
            return View();
        }

        public ActionResult NuevoEnvase()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevaMateriaPrima(string NombreMP, string DescripcionGral, int selectTipos)
        {
            var tipo = db.TiposMateriaPrima.Find(selectTipos);
            Materia_Prima mp = new Materia_Prima()
            {
                Nombre = NombreMP,
                Descripcion_Gral = DescripcionGral,
                TipoMateriaPrima = tipo
            };
            db.MateriasPrimas.Add(mp);
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult NuevoProducto(string NombreProd, string Descripcion, List<Materia_Prima> materiasPrimas)
        {
            Producto producto = new Producto()
            {
                Nombre = NombreProd,
                Descripcion = Descripcion,
                LineasProducto = new List<Linea_Producto>()
            };
            db.Productos.Add(producto);

            foreach (var materia in materiasPrimas)
            {
                Linea_Producto linea = new Linea_Producto
                {
                    IdMateria_Prima = materia.IdMateria_Prima,
                    Id_Producto = producto.Id_Producto
                };
                db.LineasProductos.Add(linea);
            }
            db.SaveChanges();
            var mp = db.MateriasPrimas.ToList();
            ViewBag.MPrimas = mp;
            return View();
        }

        [HttpPost]
        public ActionResult NuevoTipoMateriaP(string NombreTMateriaP, string Descripcion)
        {
            Tipo_MateriaPrima tipo = new Tipo_MateriaPrima()
            {
                Nombre = NombreTMateriaP,
                Descripcion = Descripcion
            };

            db.TiposMateriaPrima.Add(tipo);
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult NuevaCosecha(int AñoCosecha, string Descripcion)
        {
            Cosecha nuevaCosecha = new Cosecha()
            {
                Año = AñoCosecha,
                Descripcion = Descripcion
            };

            db.Cosechas.Add(nuevaCosecha);
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult NuevoGramaje(int PesoGramaje, string Descripcion)
        {
            Gramaje gramaje = new Gramaje()
            {
                Peso = PesoGramaje,
                Descripcion = Descripcion
            };

            db.Gramajes.Add(gramaje);
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult NuevoEnvase(string NombreEnvase, string Descripcion)
        {
            Envase envase = new Envase()
            {
                Nombre_Tipo = NombreEnvase,
                Descripcion = Descripcion
            };

            db.Envases.Add(envase);
            db.SaveChanges();
            return View();
        }
    }
}

Sw_Trazabilidad/Controllers/EmpresasController.cs
using Sw_Trazabilidad.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sw_Trazabilidad.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly Contexto db = new Contexto();
        // GET: Empresas
        public ActionResult NuevaEmpresa()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevaEmpresa(string RazonSocial, string CUIT, string Direccion)
        {
            Empresa_Proveedor empresa = new Empresa_Proveedor()
            {
                RazonSocial = RazonSocial,
                CUIT = CUIT,
                Direccion = Direccion
            };

            db.EmpresasProveedores.Add(empresa);
            db.SaveChanges();

            return View();
        }
    }
}

Sw_Trazabilidad/Controllers/ProcesosController.cs
using Sw_Trazabilidad.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Sw_Trazabilidad.Models.ViewModels;

namespace Sw_Trazabilidad.Controllers
{
    public class ProcesosController : Controller
    {
        private readonly Contexto db = new Contexto();
        // GET: Procesos
        public ActionResult NuevoProceso()
        {
            var productos = db.Productos.ToList();
            var proveedores = db.EmpresasProveedores.ToList();
            var cosechas = db.Cosechas.ToList();
            var gramajes = db.Gramajes.ToList();
            var envases = db.Envases.ToList();
            ViewBag.Proveedores = proveedores;
            ViewBag.Productos = productos;
            ViewBag.Cosechas = cosechas;
            ViewBag.Gramajes = gramajes;
            ViewBag.Envases = envases;
            return View();
        }

        [HttpPost]
        public ActionResult NuevoProceso(DateTime Fecha, bool EsRecepcion, string NombreP, int Cantidad, int CodigoProductoSalida, List<EntradaViewModel> Entradas,
            int Gramaje, int Envase, int Cosecha)
        {
            if (EsRecepcion)
            {
                var nuevoProceso = new Proceso
                {
                    Nombre = NombreP,
                    Cantidad = Cantidad,
                    Es_Recepcion = EsRecepcion,
                    Fecha_Actividad = Fecha,
                    Observaciones = "",
                };
            }
            return View();
        }


        [HttpPost]
        public ActionResult ObtenerMateriasPrimasPorProducto(int idProducto)
        {
            var materias_primas = db.LineasProductos.Include(x => x.Materiaprima)
                .Where(x => x.Id_Producto == idProducto).Select(x => new {Codigo = x.Materiaprima.IdMateria_Prima, Nombre = x.Materiaprima.Nombre}).ToList();
            return Json(materias_primas);
        }

        [HttpPost]
        public ActionResult ObtenerLotesPorLinea(int idMateriaPrima)
        {
            var lotes = db.Entradas.Include(x => x.MateriaPrima).Where(x => x.IdMateria_Prima == idMateriaPrima).Select(x => new {Id = x.Codigo_Entrada, Nombre = x.LoteEntrada }).ToList();
            var proveedores = db.EmpresasProveedores.Where(x => x.MateriasPrimas.Any(y => y.IdMateria_Prima == idMateriaPrima)).Select(x => new {Id = x.IdEmpresa_Proveedor, Nombre = x.RazonSocial }).ToList();
            var result = new { Lotes = lotes, Proveedores = proveedores };
            return Json(result);
        }
    }
}

Sw_Trazabilidad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema de trazabilidad</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ingenieria Alimentaria","Index","Home", null, new {@class = "navbar-brand"})
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Procesos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Nuevo Proceso", "NuevoProceso","Procesos")</li>
                            <li><a href="#">Gestion Procesos</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Empresas<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Nueva Empresa", "NuevaEmpresa", "Empresas")</li>
                            <li><a href="#">Gestion Empresas</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administracion<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Nueva Materia Prima", "NuevaMateriaPrima", "Administracion")</li>
                            <li>@Html.ActionLink("Nuevo Producto", "NuevoProducto", "Administracion")</li>
                            <li>@Html.ActionLink("Nuevo Tipo de Materia Prima", "NuevoTipoMateriaP", "Administracion")</li>
                            <li>@Html.ActionLink("Nueva Cosecha", "NuevaCosecha", "Administracion")</li>
                            <li>@Html.ActionLink("Nuevo Gramaje", "NuevoGramaje", "Administracion")</li>
                            <li>@Html.ActionLink("Nueva Envase", "NuevoEnvase", "Administracion")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Registro</a></li>
                    <li><a href="#">Ingresar</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SISPAC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>